In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [3]:
# 1. numpy数组创建
data1 = [1, 3, 3.6, 0, 9]
arr1 = np.array(data1)
arr1

array([1. , 3. , 3.6, 0. , 9. ])

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1 = arr1.astype(np.int32)
arr1

array([1, 3, 3, 0, 9])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr3 = np.arange(10) 
print(arr3)
print(np.arange(0, 10, .5))  # np.arange()可以将步长设置为任意实数,左闭右开;

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [8]:
arr4 = range(10)  # range()无法将步长设置为浮点数;
print(arr4)  # range()返回的是一个可迭代对象,即迭代器;
print(type(arr4))

range(0, 10)
<class 'range'>


In [9]:
arr3 = arr3 + 1
print(arr3)
print(type(arr3))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [10]:
print(np.linspace(1, 10, 20))  # 生成指定个数的数组,闭区间;
print(np.linspace(1, 10, 20, endpoint=False))  # 指定为左闭右开;

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[1.   1.45 1.9  2.35 2.8  3.25 3.7  4.15 4.6  5.05 5.5  5.95 6.4  6.85
 7.3  7.75 8.2  8.65 9.1  9.55]


In [11]:
print(np.zeros((3, 4)))
print(np.zeros(shape = [3, 4]))
print(np.zeros(shape = (3, 4)))
print(np.ones(shape = [3, 4], dtype = float))
print(np.zeros_like(arr2))  # 借用arr2的类型和尺寸;
data5 = np.arange(6)
arr5 = data5.reshape((2, 3))
print(np.ones_like(arr5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1]
 [1 1 1]]


In [12]:
arr6 = np.arange(1, 10)
print(arr6.ndim)
print(arr6.shape)
arr7 = np.arange(15)
print(arr7)
arr7_shape = arr7.reshape(3, 5)
print(arr7_shape)
print(arr5.ndim)
print(arr5.shape)  # 二维数组
print(arr5.size)
print(np.arange(30).reshape(2, 3, 5))  # 三维数组

1
(9,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
(2, 3)
6
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [13]:
# 2. nupy数组运算
# 2.1 numpy基本运算
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2 = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
list3 = [item1 + item2 for item1, item2 in zip(list1, list2)]
print(list3)
list1_arr = np.array(list1)
list2_arr = np.array(list2)
list_sum = list1_arr + list2_arr
print(list_sum)
arr1 = np.arange(10)
arr2 = np.linspace(1, 10, 10)
print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)
print(arr1 ** 2)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[12 14 16 18 20 22 24 26 28 30]
[0 1 2 3 4 5 6 7 8 9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0.  2.  6. 12. 20. 30. 42. 56. 72. 90.]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9       ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0  1  4  9 16 25 36 49 64 81]


In [14]:
# 2.2 numpy逐元素运算与张量点乘运算
arr3 = np.array([[1, 2], [3, 4]])
print(arr3)
arr4 = np.ones((2, 2))
print(arr4)
print(arr3 + arr4)
print(arr3 * arr4)
print(np.multiply(arr3, arr4))
arr5 = np.arange(9).reshape(3, 3)
arr6 = np.ones(shape = (3, 2))
print(arr5)
print(arr6)
print(np.dot(arr5, arr6))  # 使用数组模拟矩阵乘法
arr7 = np.mat(arr5)  # 将数组转化成矩阵
arr8 = np.mat(arr6)
print(arr7 * arr8)
arr9 = np.mat(np.random.random((3, 3)))  # 生成3*3的随机数矩阵
print(arr9)
print(arr9.I)  # 逆矩阵
print(arr9.T)  # 转置矩阵
print(arr9.A)  # 矩阵对应的二维数组
# print(np.ee())  # 生成单位矩阵
# print(np.dia())  # 生成对角线元素矩阵

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [4. 5.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 3.  3.]
 [12. 12.]
 [21. 21.]]
[[ 3.  3.]
 [12. 12.]
 [21. 21.]]
[[0.9607466  0.21824594 0.86550154]
 [0.26457496 0.86599081 0.17405854]
 [0.74964315 0.39398643 0.95534711]]
[[ 3.28996583  0.57450755 -3.08523302]
 [-0.53020988  1.16652722  0.26781203]
 [-2.36291587 -0.9318828   3.35721902]]
[[0.9607466  0.26457496 0.74964315]
 [0.21824594 0.86599081 0.39398643]
 [0.86550154 0.17405854 0.95534711]]
[[0.9607466  0.21824594 0.86550154]
 [0.26457496 0.86599081 0.17405854]
 [0.74964315 0.39398643 0.95534711]]


In [15]:
# 2.3 爱因斯坦求和约定(einsum)
arr10 = np.arange(10)
print(arr10)
print(np.einsum('i->', arr10))
arr11 = np.arange(20).reshape(4, 5)
print(arr11)
print(np.einsum('ij->j', arr11))  # i表示行,j表示列,这里表示按列求和;
print(np.einsum('ab->a', arr11))
arr12 = np.array([[1, 1, 1], [2, 2, 2], [5, 5, 5]])
arr13 = np.array([[0, 1, 0], [1, 1, 0], [1, 1, 1]])
print(arr12 @ arr13)  # 等价于np.dot(arr12, arr13)
print(np.einsum('ij, jk->ik', arr12, arr13))
arr14 = np.array([[1, 2], [3, 4]])
arr15 = np.ones(shape = (2, 2))
print(np.einsum('ij, ij->ij', arr14, arr15))
print(np.einsum('ii->', arr14))  # 对角线求和
print(np.einsum('ij->ji', arr14))  # 求转置矩阵

[0 1 2 3 4 5 6 7 8 9]
45
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
[[1. 2.]
 [3. 4.]]
5
[[1 3]
 [2 4]]


In [16]:
# 2.4 numpy中的轴方向
arr15 = np.ones((2, 3))
print(arr15)
print(arr15.sum())  # axis=None默认全维度约减
print(arr15.sum(axis = 0))  # 垂直方向约减
print(arr15.sum(axis = 1))  # 水平方向约减
arr16 = np.array([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])  # 有三层括号,维度由外到内分别为[0, 1, 2]
print(arr16)
print(arr16.sum(axis = 0))
print(arr16.sum(axis = 1))
print(arr16.sum(axis = 2))
print(arr16.sum(axis = 2).ndim)  # 查看约减后的维度
arr17 = np.linspace(1, 9, 9).reshape(3, 3)
print(arr17)
print(arr17.max(0), arr17.max(1), arr17.max())

[[1. 1. 1.]
 [1. 1. 1.]]
6.0
[2. 2. 2.]
[3. 3.]
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
[[4 4 4]
 [6 6 6]]
[[3 3 3]
 [7 7 7]]
[[ 3  6]
 [ 9 12]]
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[7. 8. 9.] [3. 6. 9.] 9.0


In [17]:
# 2.5 操作数组
arr18 = np.linspace(-0.5, 0.6, 12)
print(arr18)
print(arr18[0], arr18[-1])
arr18[0] = 1
print(arr18[0])
arr19 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr19[0][2], arr19[0, 2])  # 访问第0行第2列的元素
arr19[0, 2] = 100
print(arr19[0, 2])

[-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6]
-0.5 0.6
1.0
3 3
100


In [18]:
# 2.6 numpy中的切片访问
arr20 = np.arange(10)
s = slice(0, 9, 2)  # 创建切片对象
arr20_slice = arr20[s]  # 按照切片规则提取数据
print(arr20)  # 原始数组的值不受影响
print(arr20_slice)
print(arr20[0: 9: 2])
print(arr20)  # 原始数组的值不受影响
print(arr20[2:])
print(arr20[2:-2])
print(arr20[::-1])  # 逆序输出
arr21 = np.array([[1, 1, 1], [2, 2, 2], [5, 5, 5]])
print(arr21)
print(arr21.transpose())  # 转置
print(arr21.ravel())  # 二维数组展平
print(arr21.flatten())  # 二维数组展平(深拷贝)
arr21.shape = (1, -1)  # 1表示一行,-1表示让系统自动推断剩余维度
print(arr21)  

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[[1 1 1]
 [2 2 2]
 [5 5 5]]
[[1 2 5]
 [1 2 5]
 [1 2 5]]
[1 1 1 2 2 2 5 5 5]
[1 1 1 2 2 2 5 5 5]
[[1 1 1 2 2 2 5 5 5]]


In [19]:
# 2.7 numpy中的广播机制
arr22 = np.arange(3)
print(arr22.shape)
print(arr22 + 5)  # 长度为3的1D张量和0D张量(标量)相加,标量将被拉伸成为一个尺寸为(3,)的张量
arr23 = np.ones((3, 3))
arr24 = np.arange(3)
print(arr23)
print(arr24)
print(arr23 + arr24)
arr25 = np.arange(3).reshape((3, 1))
print(arr25.shape)
arr26 = np.arange(3)
print(arr25)
print(arr26.shape)
print(arr26)
print(arr25 + arr26)

(3,)
[5 6 7]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(3, 1)
[[0]
 [1]
 [2]]
(3,)
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [34]:
# 2.8 花式索引
arr27 = np.array([21, 32, 35, 56, 23, 23, 35, 57, 76, 87])
print(arr27[[1, 3, 4]])
index = [1, 3, 4]
print(arr27[index])
arr28 = np.arange(20).reshape(4, 5)
print(arr28)
print(arr28[[0, 2, 1, 0]])
index = [0, 2, 1, 0]
print(arr28[index])  # 花式索引访问行
print(arr28[:, index]) # 花式索引访问列
print(arr28[2, [1, 2, 3]])  # 第2行的1,2,3列
row_index = [0, 1, 3, 2]
col_index = [0, 1, 0, 1]
print(arr28[row_index, col_index])  # 构建[0,0],[1,1],[3,0],[2,0]四个元素,返回的原始数组的视图
row_index = np.array([0, 2, 1])  # 定义花式访问的行
col_mask = np.array([1, 0, 1, 0, 1], dtype=bool)  # 定义列访问掩码,第0,2,4列数据有效;
col_index = [0, 1, 0, 1]
print(arr28[row_index[:, np.newaxis], col_mask])

[32 56 23]
[32 56 23]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 0  2  1  0]
 [ 5  7  6  5]
 [10 12 11 10]
 [15 17 16 15]]
[11 12 13]
[ 0  6 15 11]
[[ 0  2  4]
 [10 12 14]
 [ 5  7  9]]


In [40]:
# 2.9 布尔索引
arr29 = np.arange(10).reshape(2, 5)
print(arr29)
print(arr29[arr29 > 5])
print(arr29 > 5)
print(arr29 % 2 == 0)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[6 7 8 9]
[[False False False False False]
 [False  True  True  True  True]]
[[ True False  True False  True]
 [False  True False  True False]]


In [59]:
# 2.10 数组堆叠操作
arr30 = np.zeros(shape = (2, 2), dtype = np.int)
arr31 = np.ones(shape = (2, 3), dtype = np.int)
print(np.hstack((arr30, arr31)))  # 水平方向堆叠,要求行尺寸相同
print(np.concatenate((arr30, arr31), axis = 1))  # 使用concatenate()能够达到一样的效果
arr32 = np.zeros(shape = (2, 3), dtype = np.int)
arr33 = np.ones(shape = (3, 3), dtype = np.int)
print(np.vstack((arr32, arr33)))
print(np.concatenate((arr32, arr33), axis = 0))  # 使用concatenate()
arr34 = np.arange(0, 9)
arr35 = np.arange(9, 18)
arr36 = np.arange(18, 27)
print(np.dstack((arr34, arr35, arr36)))  # 深度方向堆叠
arr37 = np.arange(0, 9).reshape(3, 3)
arr38 = np.arange(9, 18).reshape(3, 3)
arr39 = np.arange(18, 27).reshape(3, 3)
print(np.dstack((arr37, arr38, arr39)))

[[0 0 1 1 1]
 [0 0 1 1 1]]
[[0 0 1 1 1]
 [0 0 1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[[ 0  9 18]
  [ 1 10 19]
  [ 2 11 20]
  [ 3 12 21]
  [ 4 13 22]
  [ 5 14 23]
  [ 6 15 24]
  [ 7 16 25]
  [ 8 17 26]]]
[[[ 0  9 18]
  [ 1 10 19]
  [ 2 11 20]]

 [[ 3 12 21]
  [ 4 13 22]
  [ 5 14 23]]

 [[ 6 15 24]
  [ 7 16 25]
  [ 8 17 26]]]


C:\Users\zhangcy4\AppData\Local\Temp\ipykernel_31064\1988017781.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr30 = np.zeros(shape = (2, 2), dtype = np.int)
C:\Users\zhangcy4\AppData\Local\Temp\ipykernel_31064\1988017781.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, che

In [69]:
# 2.11 列堆叠和行堆叠
arr40 = np.arange(3)
arr41 = arr40 * 2
print(np.column_stack((arr40, arr41)))  # 列方向堆叠;
arr42 = np.arange(9).reshape(3, 3)
arr43 = arr42 * 2
print(np.column_stack((arr42, arr43)))
print(np.column_stack((arr42, arr43)) == np.hstack((arr42, arr43)))  # 和hstack()等价;
print(np.row_stack((arr42, arr43)))  # 行方向堆叠;
print(np.row_stack((arr42, arr43)) == np.vstack((arr42, arr43)))  # 和vstack()等价;

[[0 0]
 [1 2]
 [2 4]]
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]]
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [89]:
# 2.12 数组的分割操作(hslpit(),vsplit(),dsplit())
arr44 = np.arange(16.0).reshape(4, 4)
print(arr44)
print(np.hsplit(arr44, 2))  # 列方向分割,相当于axis=1
print(np.hsplit(arr44, 2)[0])
print(type(np.hsplit(arr44, 2)), len(np.hsplit(arr44, 2)))
arr45 = np.arange(16.0).reshape(2, 8)
print(arr45)
print(np.hsplit(arr45, [2, 4, 6]))  # 等价于设置axis=1
print(np.vsplit(arr45, 2))  # 水平方向分割
print(np.split(arr45, 2, axis = 0))  # split()配合axis=0实现
arr46 = np.arange(16.0).reshape(2, 2, 4) # 两个2*4矩阵
print(arr46)
print(np.dsplit(arr46, 2))
print(np.split(arr46, [1,], axis = 2)) # 设置axis=2等价于dsplit()

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]
[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]]
<class 'list'> 2
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12. 13. 14. 15.]]
[array([[0., 1.],
       [8., 9.]]), array([[ 2.,  3.],
       [10., 11.]]), array([[ 4.,  5.],
       [12., 13.]]), array([[ 6.,  7.],
       [14., 15.]])]
[array([[0., 1., 2., 3., 4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11., 12., 13., 14., 15.]])]
[array([[0., 1., 2., 3., 4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11., 12., 13., 14., 15.]])]
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]
[array([[[ 0.],
        [ 4.]],

In [96]:
# 2.13 numpy中的random模块
rdm = np.random.RandomState(1)  # 定义随机种子
np.random.seed(19680101)  # 定义随机种子
rand = np.random.rand(2, 3)  # 生成2*3的随即数组,服从均匀分布
print("rand(d0, d1,...,dn):生成标准均匀分布的随机数\n", rand)
randn = np.random.rand(2, 3)  # 生成2*3的随即数组,服从正态分布
print("rand(d0, d1,...,dn):生成标准正态分布的随机数\n", randn)
randint = np.random.randint(1, 10, (2, 3)) # 生成2*3的1-10的随机整数
print("randint(low, high, size, dtype):生成随机整数\n", randint)
random = np.random.random((2, 3))
print("randint(size):在[0, 1)内生成随机数\n", random)
# (b - a) * np.random.rand() * a生成[a, b)范围的随机数

rand(d0, d1,...,dn):生成标准均匀分布的随机数
 [[0.23675601 0.59353868 0.74897519]
 [0.66065819 0.8813292  0.93499822]]
rand(d0, d1,...,dn):生成标准正态分布的随机数
 [[0.03835945 0.87038464 0.84036223]
 [0.89930338 0.16414639 0.18839459]]
randint(low, high, size, dtype):生成随机整数
 [[5 6 9]
 [4 9 9]]
randint(size):在[0, 1)内生成随机数
 [[0.79630321 0.24302916 0.80162383]
 [0.64013314 0.23206275 0.80510758]]
