In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [3]:
# 1. numpy数组创建
data1 = [1, 3, 3.6, 0, 9]
arr1 = np.array(data1)
arr1

array([1. , 3. , 3.6, 0. , 9. ])

In [4]:
arr1.dtype

dtype('float64')

In [5]:
arr1 = arr1.astype(np.int32)
arr1

array([1, 3, 3, 0, 9])

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr3 = np.arange(10) 
print(arr3)
print(np.arange(0, 10, .5))  # np.arange()可以将步长设置为任意实数,左闭右开;

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [8]:
arr4 = range(10)  # range()无法将步长设置为浮点数;
print(arr4)  # range()返回的是一个可迭代对象,即迭代器;
print(type(arr4))

range(0, 10)
<class 'range'>


In [9]:
arr3 = arr3 + 1
print(arr3)
print(type(arr3))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [10]:
print(np.linspace(1, 10, 20))  # 生成指定个数的数组,闭区间;
print(np.linspace(1, 10, 20, endpoint=False))  # 指定为左闭右开;

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[1.   1.45 1.9  2.35 2.8  3.25 3.7  4.15 4.6  5.05 5.5  5.95 6.4  6.85
 7.3  7.75 8.2  8.65 9.1  9.55]


In [11]:
print(np.zeros((3, 4)))
print(np.zeros(shape = [3, 4]))
print(np.zeros(shape = (3, 4)))
print(np.ones(shape = [3, 4], dtype = float))
print(np.zeros_like(arr2))  # 借用arr2的类型和尺寸;
data5 = np.arange(6)
arr5 = data5.reshape((2, 3))
print(np.ones_like(arr5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0 0 0 0]
 [0 0 0 0]]
[[1 1 1]
 [1 1 1]]


In [12]:
arr6 = np.arange(1, 10)
print(arr6.ndim)
print(arr6.shape)
arr7 = np.arange(15)
print(arr7)
arr7_shape = arr7.reshape(3, 5)
print(arr7_shape)
print(arr5.ndim)
print(arr5.shape)  # 二维数组
print(arr5.size)
print(np.arange(30).reshape(2, 3, 5))  # 三维数组

1
(9,)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
(2, 3)
6
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [13]:
# 2. nupy数组运算
# 2.1 numpy基本运算
list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list2 = [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
list3 = [item1 + item2 for item1, item2 in zip(list1, list2)]
print(list3)
list1_arr = np.array(list1)
list2_arr = np.array(list2)
list_sum = list1_arr + list2_arr
print(list_sum)
arr1 = np.arange(10)
arr2 = np.linspace(1, 10, 10)
print(arr1)
print(arr2)
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 % arr2)
print(arr1 ** 2)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
[12 14 16 18 20 22 24 26 28 30]
[0 1 2 3 4 5 6 7 8 9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[ 0.  2.  6. 12. 20. 30. 42. 56. 72. 90.]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9       ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0  1  4  9 16 25 36 49 64 81]


In [14]:
# 2.2 numpy逐元素运算与张量点乘运算
arr3 = np.array([[1, 2], [3, 4]])
print(arr3)
arr4 = np.ones((2, 2))
print(arr4)
print(arr3 + arr4)
print(arr3 * arr4)
print(np.multiply(arr3, arr4))
arr5 = np.arange(9).reshape(3, 3)
arr6 = np.ones(shape = (3, 2))
print(arr5)
print(arr6)
print(np.dot(arr5, arr6))  # 使用数组模拟矩阵乘法
arr7 = np.mat(arr5)  # 将数组转化成矩阵
arr8 = np.mat(arr6)
print(arr7 * arr8)
arr9 = np.mat(np.random.random((3, 3)))  # 生成3*3的随机数矩阵
print(arr9)
print(arr9.I)  # 逆矩阵
print(arr9.T)  # 转置矩阵
print(arr9.A)  # 矩阵对应的二维数组
# print(np.ee())  # 生成单位矩阵
# print(np.dia())  # 生成对角线元素矩阵

[[1 2]
 [3 4]]
[[1. 1.]
 [1. 1.]]
[[2. 3.]
 [4. 5.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[ 3.  3.]
 [12. 12.]
 [21. 21.]]
[[ 3.  3.]
 [12. 12.]
 [21. 21.]]
[[0.57230532 0.53915083 0.23208058]
 [0.431719   0.48291885 0.13254163]
 [0.51038343 0.40070833 0.26815055]]
[[ 106.29052753  -71.77043993  -56.51823646]
 [ -66.95809344   48.72258222   33.86867072]
 [-102.24949473   63.79587421   60.69170075]]
[[0.57230532 0.431719   0.51038343]
 [0.53915083 0.48291885 0.40070833]
 [0.23208058 0.13254163 0.26815055]]
[[0.57230532 0.53915083 0.23208058]
 [0.431719   0.48291885 0.13254163]
 [0.51038343 0.40070833 0.26815055]]


In [28]:
# 2.3 爱因斯坦求和约定(einsum)
arr10 = np.arange(10)
print(arr10)
print(np.einsum('i->', arr10))
arr11 = np.arange(20).reshape(4, 5)
print(arr11)
print(np.einsum('ij->j', arr11))  # i表示行,j表示列,这里表示按列求和;
print(np.einsum('ab->a', arr11))
arr12 = np.array([[1, 1, 1], [2, 2, 2], [5, 5, 5]])
arr13 = np.array([[0, 1, 0], [1, 1, 0], [1, 1, 1]])
print(arr12 @ arr13)  # 等价于np.dot(arr12, arr13)
print(np.einsum('ij, jk->ik', arr12, arr13))
arr14 = np.array([[1, 2], [3, 4]])
arr15 = np.ones(shape = (2, 2))
print(np.einsum('ij, ij->ij', arr14, arr15))
print(np.einsum('ii->', arr14))  # 对角线求和
print(np.einsum('ij->ji', arr14))  # 求转置矩阵

[0 1 2 3 4 5 6 7 8 9]
45
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[10 35 60 85]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
[[ 2  3  1]
 [ 4  6  2]
 [10 15  5]]
[[1. 2.]
 [3. 4.]]
5
[[1 3]
 [2 4]]


In [41]:
# 2.4 numpy中的轴方向
arr15 = np.ones((2, 3))
print(arr15)
print(arr15.sum())  # axis=None默认全维度约减
print(arr15.sum(axis = 0))  # 垂直方向约减
print(arr15.sum(axis = 1))  # 水平方向约减
arr16 = np.array([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])  # 有三层括号,维度由外到内分别为[0, 1, 2]
print(arr16)
print(arr16.sum(axis = 0))
print(arr16.sum(axis = 1))
print(arr16.sum(axis = 2))
print(arr16.sum(axis = 2).ndim)  # 查看约减后的维度
arr17 = np.linspace(1, 9, 9).reshape(3, 3)
print(arr17)
print(arr17.max(0), arr17.max(1), arr17.max())

[[1. 1. 1.]
 [1. 1. 1.]]
6.0
[2. 2. 2.]
[3. 3.]
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]]
[[4 4 4]
 [6 6 6]]
[[3 3 3]
 [7 7 7]]
[[ 3  6]
 [ 9 12]]
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[7. 8. 9.] [3. 6. 9.] 9.0


In [51]:
# 2.5 操作数组
arr18 = np.linspace(-0.5, 0.6, 12)
print(arr18)
print(arr18[0], arr18[-1])
arr18[0] = 1
print(arr18[0])
arr19 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr19[0][2], arr19[0, 2])  # 访问第0行第2列的元素
arr19[0, 2] = 100
print(arr19[0, 2])

[-0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6]
-0.5 0.6
1.0
3 3
100


In [68]:
# 2.6 numpy中的切片访问
arr20 = np.arange(10)
s = slice(0, 9, 2)  # 创建切片对象
arr20_slice = arr20[s]  # 按照切片规则提取数据
print(arr20)  # 原始数组的值不受影响
print(arr20_slice)
print(arr20[0: 9: 2])
print(arr20)  # 原始数组的值不受影响
print(arr20[2:])
print(arr20[2:-2])
print(arr20[::-1])  # 逆序输出
arr21 = np.array([[1, 1, 1], [2, 2, 2], [5, 5, 5]])
print(arr21)
print(arr21.transpose())  # 转置
print(arr21.ravel())  # 二维数组展平
print(arr21.flatten())  # 二维数组展平(深拷贝)
arr21.shape = (1, -1)  # 1表示一行,-1表示让系统自动推断剩余维度
print(arr21)  

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]
[[1 1 1]
 [2 2 2]
 [5 5 5]]
[[1 2 5]
 [1 2 5]
 [1 2 5]]
[1 1 1 2 2 2 5 5 5]
[1 1 1 2 2 2 5 5 5]
[[1 1 1 2 2 2 5 5 5]]


In [81]:
# 2.7 numpy中的广播机制
arr22 = np.arange(3)
print(arr22.shape)
print(arr22 + 5)  # 长度为3的1D张量和0D张量(标量)相加,标量将被拉伸成为一个尺寸为(3,)的张量
arr23 = np.ones((3, 3))
arr24 = np.arange(3)
print(arr23)
print(arr24)
print(arr23 + arr24)
arr25 = np.arange(3).reshape((3, 1))
print(arr25.shape)
arr26 = np.arange(3)
print(arr25)
print(arr26.shape)
print(arr26)
print(arr25 + arr26)

(3,)
[5 6 7]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
(3, 1)
[[0]
 [1]
 [2]]
(3,)
[0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
